##################################### TIENDAS.
GET http://localhost:8000/stores

### Obtener tienda por ID.
GET http://localhost:8000/stores/1

### Crear tienda.
POST http://localhost:8000/stores
Content-Type: application/json

{
    "name": "comicom",
    "description": "venta de comics",
    "user": "1",
    "address": "hahahah"
    
}

### Actualizar tienda.
PUT http://localhost:8000/stores/1
Content-Type: application/json

{
    "name": "Mi nuevo libro (edición 2)",
    "description": "Hans A.C.",
    "user": "110"
}

### Borrar tienda.
DELETE http://localhost:8000/stores/2



######################################  ROLES


### Obtener todos las roles.
GET http://localhost:8000/roles

### Obtener rol por ID.
GET http://localhost:8000/roles/1

### Crear roles.
POST http://localhost:8000/roles
Content-Type: application/json

{
    "name": "Admin",
    "description": "super user"
}

### Actualizar roles.
PUT http://localhost:8000/roles/1
Content-Type: application/json

{
    "name": "Tienda",
    "description": "usuario de tienda"
}

### Borrar roles.
DELETE http://localhost:8000/roles/1


#########################################  PRODUCTOS


### Obtener todos las productos.
GET http://localhost:8000/products

### Obtener producto por ID.
GET http://localhost:8000/products/1

### Crear productos.
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Mi nuevo libro",
    "description": "Hans A.C.",
    "quantity": 100
}

### Actualizar productos.
PUT http://localhost:8000/products/1
Content-Type: application/json

{
    "name": "Mi nuevo libro",
    "description": "Hans A.C.",
    "quantity": 100
}

### Borrar productos.
DELETE http://localhost:8000/products/1


#####################################  USUARIO


### Obtener todos las usuarios.
GET http://localhost:8000/users

### Obtener usuario por ID.
GET http://localhost:8000/users/1

### Crear usuario.
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Mi nuevo libro",
    "email": "Hans A.C.",
    "shipping_addres": "100",
    "role": "1"
}

### Actualizar usuario.
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "name": "Mi nuevo libro",
    "email": "Hans A.C.",
    "shipping_addres": "100",
    "role": "1"
}

### Borrar usuario.
DELETE http://localhost:8000/users/1